@rootAPI=http://localhost:8000/api/v1


#=========== Admin API

### Create new admin
POST {{rootAPI}}/admin
Content-Type: application/json

{
    "fname":"Bijay",
     "lname":"Nagarkoti",
     "phone":"0410584026",
     "email":"nb@gmail.com",
     "password":"a",
     "address":""
}

### Login in
POST {{rootAPI}}/admin/sign-in
Content-Type: application/json

{
    "email":"bnag@gmail.com",
    "password":"11111111"
}

#============ Category API
###
POST {{rootAPI}}/category
Content-Type: application/json

{
    "title":"Furnitures"
}
###
GET {{rootAPI}}/category
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJuYWdAZ21haWwuY29tIiwiaWF0IjoxNjkwNjc5NjE5LCJleHAiOjE2OTA2Nzk2MjB9.mUAK4N2yI4s-ev7Zj0saBZA_h-IZe_n5k9nhTfrRaGI

#===========Request new Access JWT API =============
### GET NEW ACCESS TOKEN
GET {{rootAPI}}/admin/get-accessjwt
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJuYWdAZ21haWwuY29tIiwiaWF0IjoxNjkwOTc2OTA5LCJleHAiOjE2OTM1Njg5MDl9.Kpxu2IMLYov75kIDg86rvnQHfsr8td4P2GYlnlp8AjA



##############  Payment Options ##########
### POST NEW PAYMENT OPTION
POST {{rootAPI}}/payment-options
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJuYWdAZ21haWwuY29tIiwiaWF0IjoxNjkxMjc5OTc3LCJleHAiOjE2OTEyODA4Nzd9.czGXwY6xtnHEqZmoq0PoA2adt67p2n70Cp0TSeVpH7A
Content-Type: application/json

{
    "status":"inactive",
    "title":"PayID",
    "description":"Please use the following PayID to complete the payment for the purchase."
}

### Get all payments
GET {{rootAPI}}/payment-options
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJuYWdAZ21haWwuY29tIiwiaWF0IjoxNjkxMjgxNDYzLCJleHAiOjE2OTEyODIzNjN9.c_unn3095Z3-ql4a0nPWqpb7O2HgSnldA_JtzMHLHpY


############## Product API ###########
### Get Products
GET {{rootAPI}}/product


